### ISSUE TITLE
Unable to change the Application Name in Info.plist

### ISSUE THREAD

**Issue by chxxangie** [ytabuchi/XamarinFormsPCLTemplate#8]
In the IOS project template, I replaced the Application Name with $ext_safeprojectname$ which is to capture the Project Name in Info.plist, but it is not replaced when i create new project with this project template. 
`<string>$ext_safeprojectname$</string>`

Similar thing i did in Android project template, it is able to capture $ext_safeprojectname$ in MainActicity.cs.

**Comment by ytabuchi** [comment]
Thank you for reporting. 
I’ll check and fix the issue soon. 

Also I have to update version of Xamarin.Forms.

**Comment by chxxangie** [comment]
> Thank you for reporting.
> I’ll check and fix the issue soon.
> 
> Also I have to update version of Xamarin.Forms.

Thanks for looking into this issue. This XamarinFormsPCLTemplate has helped me to save a lot of time! Really appreciate it!!

**Comment by ytabuchi** [comment]
@chxxangie 
I understood your problem. 
In `ROOTDIR\XFPCLApp.iOS\MyTemplate.vstemplate`, `Info.plist` file has set as `ReplaceParameters=false`. So that your change could not applied to the file. 

I fixed it. Thank you 👍

**Comment by chxxangie** [comment]
Glad to hear that... Thanks for fixing it!!!
